<?php

namespace Jhonny\Bundle\AdministradorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LineaFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaFacturaRepository extends EntityRepository
{
}
